server:
  port: ${SERVER_PORT:18080}

spring:
  application:
    name: payledger-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18081/realms/payledger-local}
          audiences:
            - ${KEYCLOAK_AUDIENCE:payledger-api}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:55433}/${POSTGRES_DB:payledger}
    username: ${POSTGRES_USER:payledger_app}
    password: ${POSTGRES_PASSWORD:payledger_dev_only}

  jackson:
    time-zone: UTC

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    clean-disabled: true
    validate-migration-naming: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
